Completed Responsive Web Design
appiersign/The-Next-Web pull request #4
Opened 2020-01-30 17:37 UTC by appiersign

#### In This Pull Request We Worked on:
- adding semantic HTML elements
- styling various element to match the original website
- used both flexbox and the grid template to make the site responsive
- added font awesome icons for social media links
- added a gitignore file to exempt files and directories from being tracked
- fixed html validated errors

2020-01-30 23:57 UTC, MauricioRobayo requested changes
Hi!

The project is looking great 🥇, very nice use of Flexbox and CSS Grid, also a nice use of semantic HTML.

There are some requirements that are not met yet:

### Small version
* [x] Navigation and sub-navigation row change to a hamburger (bars) icon at the rightmost part (next to search icon).
### Medium version
* [x] Top 3 articles the TWN logo at the top left corner of the row disappears:
![image](https://user-images.githubusercontent.com/2121481/73500614-3105bd00-4391-11ea-860b-4f0428a89033.png)
### Large version
* [x] Lastest deal section aligns 4 deals per row, this is how it is looking now:
![image](https://user-images.githubusercontent.com/2121481/73500825-c1440200-4391-11ea-8871-2907545e6af4.png)

Status: **Request changes**.

2020-01-31 17:21 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-01-31 17:49 UTC, addod19 requested changes
## Status: Require changes 🔴

**Hi Team**, congratulations on the effort in this project :+1:   Your project looks really great but for the project to be approved, we have to make small changes to the project :slightly_smiling_face: Below is the comment:
- It contains social media icons
![smi](https://user-images.githubusercontent.com/46388113/73561595-1c1b3f00-440e-11ea-846c-9077a3fb348d.PNG)
Like this
![like](https://user-images.githubusercontent.com/46388113/73561683-47059300-440e-11ea-8321-e83fad94d76e.PNG)

- Kindly check the horizontal scroll at a small screen size
![SC](https://user-images.githubusercontent.com/46388113/73561491-f4c47200-440d-11ea-9e3d-e24aff851003.PNG)
- It contains TNW logo
![TNW](https://user-images.githubusercontent.com/46388113/73561761-73211400-440e-11ea-8cd0-11af5816ac79.PNG)
Like this
![like2](https://user-images.githubusercontent.com/46388113/73561806-90ee7900-440e-11ea-8b80-e080cdee6c90.PNG)

Kindly make these changes and submit code review :100: 
Happy coding :computer: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

2020-01-31 19:19 UTC, pelzolga123 commented on index.html
> +  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
This commented line should be removed.

2020-01-31 19:19 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: great!
Here are the things that need fixing:
* [ ] First section is a little messed up in large and medium versions, you need to align pictures properly. Right now it looks like this:
![image](https://user-images.githubusercontent.com/20416431/73567051-279e5280-446e-11ea-804f-cbbd2867fd36.png)
* [ ] It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
 
### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-01-31 22:08 UTC, Anna-Myzukina commented
### Pull Request under the review by Anna Muzykina (TSE)

2020-01-31 22:13 UTC, Anna-Myzukina commented
## Hi team!
### Nice job! Project looks! :+1: 

## Status [Approved]







#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding

2020-01-31 22:13 UTC, Anna-Myzukina approved these changes

2020-01-31 22:45 UTC, merged